### ISSUE TITLE
model checkpoint 

### ISSUE THREAD

**Issue by itsvinayhegde** [JinZhuXing/Fingerprint_TF#10]
Hi, 

i have started training on my custom dataset, but after every epoch, it is getting saved by the same name and getting rewritten after evry epoch. Also, i had given 200 epochs, a file has been created in model/result folder named fp160_160.h5 and it has once agin started from 0th epoch. 

`Epoch 00090: saving model to /home/vinay/github_repo/Fingerprint_TF/model/checkpoint/cp_160_160.ckpt`

could you Please provide a way to save a model after every 5th or 10th epoch and naming convention for saved epoch?

 Thank you

**Comment by itsvinayhegde** [comment]
my models are getting saved as cp_160_160.ckpt.data-00000-of-00001.. and when i run the eval.py with all the parameters i am getting `ValueError: You are trying to restore a checkpoint from a legacy Keras optimizer into a v2.11+ Optimizer, which can cause errors. Please update the optimizer referenced in your code to be an instance of `tf.keras.optimizers.legacy.Optimizer`, e.g.: `tf.keras.optimizers.legacy.RMSprop`.
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
`

**Comment by JinZhuXing** [comment]
Please send me the version of the Tensorflow which you are using now.
Thank you.

**Comment by itsvinayhegde** [comment]
It's the latest version. 2.12.0

Also `model/result/fp160_160.h5` has been created. how can i use the model to predict for other images.

**Comment by JinZhuXing** [comment]
This project now load weights only for evaluation.
You can check it at eval.py line 54.
``` python
model.load_weights(checkpoint_path)
```

If you want to use .h5 file, you can use like this.
``` python
# load model
model_path = '../../model/result/fp160.h5'
model_dir = os.path.dirname(model_path)
model = tf.keras.models.load_model(model_path)
model.summary()
```

Please check it.

**Comment by JinZhuXing** [comment]
Also, you can check this version. (v0.1)
It used h5 file for model evaluation.
Please check `source\03_evaluation\03_01_eval_data.py` line 32 - 36.

**Comment by itsvinayhegde** [comment]
Thank you.. I'll check and get back to  you
