### ISSUE TITLE
Training never stopped

### ISSUE THREAD

**Issue by KeerthanaparthibanM** [JinZhuXing/Fingerprint_TF#11]
I have trained with 200 images..
`python3 source/train.py --image_width 160 --image_height 160 --dataset_path dataset/original/ --check_point model/checkpoint/ --save_model 2  --save_model_path model/result/ --train_epoch 5  --eval_num 20`

these are my parameters. The training never stops.  It's  been running for last one hour.
is there any bug in the code? 
I am not able to figure out what is happening. Please explain it to me why it is happening.Also suggest me how to proceed forward

 

Thanks

**Comment by JinZhuXing** [comment]
Thank you for your support.
I want to ask you which branch did you test?
Thanks again for your support and help.
I will try my best to support you.

**Comment by JinZhuXing** [comment]
I made train loop as endless. Please check train.py line 144.
`train_epoch` parameter means epoch count for one training.
After training it will save model as .h5 file and evaluate model.
After evaluating it will continue training.

If you want to stop after once training, you can remove line 144.
Please check.

**Comment by KeerthanaparthibanM** [comment]
> I made train loop as endless. Please check train.py line 144. `train_epoch` parameter means epoch count for one training. After training it will save model as .h5 file and evaluate model. After evaluating it will continue training.
> 
> If you want to stop after once training, you can remove line 144. Please check.

**Comment by KeerthanaparthibanM** [comment]
> > I made train loop as endless. Please check train.py line 144. `train_epoch` parameter means epoch count for one training. After training it will save model as .h5 file and evaluate model. After evaluating it will continue training.
> > If you want to stop after once training, you can remove line 144. Please check.

Thanks for the response
