### ISSUE TITLE
How to compare/verify with fingerprint using pretrained model

### ISSUE THREAD

**Issue by Ehtasha** [JinZhuXing/Fingerprint_TF#2]
Hy @JinZhuXing ,

Thanks for providing this repositories

Can we use this code to compare/verify fingerprint ?

I have setup this and run this code using pre-trained model.
I want to do fingerprint verification.

In this code after image pre-processing .npy files are generated in np_data folder.

And after running evaluation script this script not ask to provide a single image for which we need to compare/verify.

How can we customize this according to our use-case ?

**Comment by JinZhuXing** [comment]
@Ehtasha Thank you for your interest in my project.
I just added 03_04_eval_image.py file for compare/verify single fingerprint image.
Please check master branch.
Thank you.

**Comment by Ehtasha** [comment]
Thanks for reply.

Yes I have run this script. But it always give error on 'input_img' line no 52.

Error Statement: ```
Traceback (most recent call last):
  File "C:/Users/Lenovo/PycharmProjects/Fingerprint_TF-master/source/03_evaluation/03_04_eval_image.py", line 52, in <module>
    input_img = img_real[input_idx].reshape((1, 160, 160, 1)).astype(np.float32) / 255.
NameError: name 'img_real' is not defined
```

Same thing running on other scripts file without any separate initialization of 'img_real'.

**Comment by JinZhuXing** [comment]
Sorry, I didn't removed original code.
I did fix it.
Please check it again.
Thank you.

**Comment by Ehtasha** [comment]
Thanks for quick reply.

Yes I have download code again from master repository and last script (03_04_eval_image.py) is also working now.

I still have some confusion.

Can you please provide me your email ?

**Comment by JinZhuXing** [comment]
Thank you for your help.
This project is my research project, and still has many problems.
Please help me for improve performance.
Thank you very much.
My email address is peace1019@126.com

**Comment by Ehtasha** [comment]
@JinZhuXing  Thanks for sharing email also

This issue resolved now
