### ISSUE TITLE
Data set original folder not available 

### ISSUE THREAD

**Issue by filzahamjad** [JinZhuXing/Fingerprint_TF#5]
Dataset's original folder not available in the dataset i downloaded from kaggle.
baidu isn't available in my area can you kindly share the link of of the dataset on google drive?

**Comment by JinZhuXing** [comment]
@filzahamjad Thank you for your interest in my project.
Now, I have no google account. But I'll try to make a account and share dataset to you.
Please wait.
Thank you.

**Comment by JinZhuXing** [comment]
I just uploaded data to Google Drive.
https://drive.google.com/file/d/1ArZ9ECb9fCDW0UUGzeugaeMBT3_FD7U0/view?usp=sharing
Please check this URL.
If you have any question, please tell me.
Thank you.

**Comment by filzahamjad** [comment]
python3 source/01_preprocess/ 01_02_prepare_real_data.py i wrote this in terminal to run the project 
but i'm getting the error: can't find '__main__' module in 'source/01_preprocess/'

**Comment by JinZhuXing** [comment]
May I close this issue?

**Comment by filzahamjad** [comment]
Yes, Thankyou so much for your help!
