### ISSUE TITLE
Questions on Data Source

### ISSUE THREAD

**Issue by Reapor-Yurnero** [JinZhuXing/Fingerprint_TF#6]
It seems the dataset you're sharing on Kaggle and GDrive has only 10 fingers (800 images) but the pretrained model you provided are trained with much larger dataset. Could you please give a pointer to those data sources?

**Comment by JinZhuXing** [comment]
Thank you for your interest in my project.
I am very sorry.
The dataset which I was used for train is many people's donated data.
I can't share it because of the privacy policy.
If you have your own dataset then you can use it with our source code (prepare part).
Thank you.
