### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/img_val.npy'

### ISSUE THREAD

**Issue by itsvinayhegde** [JinZhuXing/Fingerprint_TF#8]
while training with sample dataset provided in dataset/ReadME.md file, i am getting this error.

**Comment by JinZhuXing** [comment]
Thank you for your support.
I am now updating model network and project structures.
So, there are many changes, but I didn't update README files yet.
I will update and cleanup project.

You can now test current project with following steps:
- Download sample dataset or your own dataset.
- Please execute make_dataset.py for prepare dataset.
```
cd source
python make_dataset.py
```
You can use every arguments for prepare dataset. You can check the instruction of the argument at make_dataset.py file (line 71 - 78)
- After preparing dataset, you can train with train.py file
```
python train.py
```
Also, you can use every arguments for custom training. (check train.py at line 197 - 212)

Please try with it now. I will update README files as soon as possible.
Thank you for your support.
I need for your continuous help and support.
Thanks again.

**Comment by itsvinayhegde** [comment]
Thank you @JinZhuXing  for the quick support.
Cheers :)
