### ISSUE TITLE
codebase not updated

### ISSUE THREAD

**Issue by itsvinayhegde** [JinZhuXing/Fingerprint_TF#9]
in the dataset/ReadME.md file, for train_data real_data and np_data, 3 separate scripts are mentioned, so that the respective folders are created. But the scripts mentioned in the files are not present in this repository. Please add the scripts required for creating the dataset to the main branch.
Thanks in advance. :)

**Comment by JinZhuXing** [comment]
Please check it.

https://github.com/JinZhuXing/Fingerprint_TF/issues/8#issuecomment-1505208368

Thank you for your support.
